spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ev_charging
    username: postgres
    password: 1105
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true